package com.jstn9.expensetracker.exception;

public enum ErrorCode {
    CATEGORY_ALREADY_EXISTS,
    CATEGORY_NOT_FOUND,
    CATEGORY_IN_USE,
    VALIDATION_FAILED,
    PROFILE_NOT_FILLED,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    USERNAME_NOT_FOUND,
    BAD_CREDENTIALS,
    JSON_INVALID,
    MALFORMED_JSON,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    TRANSACTION_NOT_FOUND,
    BALANCE_IS_NEGATIVE,
    ROLE_NOT_FOUND,
    PROFILE_NOT_FOUND
}
